name: Update package.json version

on:
  push:
    tags:
      - 'v*.*.*' # This will trigger the workflow for tags in the format vx.x.x

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Validate and extract version from tag
      id: get_version
      run: |
        TAG_NAME=${GITHUB_REF#refs/tags/}
        VERSION=${TAG_NAME#v}
        # Validate if the extracted version is in semver format
        if [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "::set-output name=version::$VERSION"
        else
          echo "Error: Invalid semver format"
          exit 1
        fi

    - name: Update package.json
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        jq ".version=\"$VERSION\"" package.json > package.tmp.json && mv package.tmp.json package.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add package.json
        git commit -m "Update package.json version to ${{ steps.get_version.outputs.version }}"
        git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master

